server:
  host: localhost
  port: 3000
  domain: example.com

env:
  enviroinment: local
  logLevel: debug
  name: app
  version: 0.0.0

secret: secret

db:
  client: mongodb
  connect: localhost
  port: 27017
  database: 'test'

api:
  host: http://car1.i.cacf.cn

cache:
  host: localhost
  port: 6379
